//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class hubV2_DNTripMB
    {
        public string DELIVERY_NUMBER { get; set; }
        public string TRIP_NUMBER { get; set; }
        public string CARRIERS_ALL { get; set; }
        public string TO_CITY { get; set; }
        public string SO_TYPE { get; set; }
        public string CARRIER_EFFECTIVE_TIME_1 { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public string CREATE_USERNAME { get; set; }
        public int FTP_STATUS { get; set; }
        public string EXPRESS_NUMBER { get; set; }
    }
}
