//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProEntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACC_MINIEHUBEntities : DbContext
    {
        public ACC_MINIEHUBEntities()
            : base("name=ACC_MINIEHUBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hubV2_DNTripMB> hubV2_DNTripMB { get; set; }
        public virtual DbSet<SODETAIL> SODETAILs { get; set; }
        public virtual DbSet<SOHEAD> SOHEADs { get; set; }
    }
}
