//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SODETAIL
    {
        public System.Guid PK_SODETAIL { get; set; }
        public int PK_SOHEAD { get; set; }
        public int LINENUMBER { get; set; }
        public string LINENUM { get; set; }
        public string DELIVERY_DETAIL_ID { get; set; }
        public string SO_LINE_ID { get; set; }
        public string PART_NO { get; set; }
        public int QUANTITY { get; set; }
        public Nullable<int> SALES_QUANTITY { get; set; }
        public Nullable<System.DateTime> SALES_DATE { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY_DATE { get; set; }
        public string REMARK { get; set; }
        public string S_L { get; set; }
    
        public virtual SOHEAD SOHEAD { get; set; }
    }
}
