//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOHEAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOHEAD()
        {
            this.SODETAILs = new HashSet<SODETAIL>();
        }
    
        public int PK_SOHEAD { get; set; }
        public string SONUMBER { get; set; }
        public string CARRIER { get; set; }
        public string CARRIER_TYPE { get; set; }
        public string CARRIER_EFFECTIVE_TIME { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string ACCOUNT_NAME_SHORT { get; set; }
        public string ACCOUNT_NAME_CODE { get; set; }
        public string MEMO { get; set; }
        public string COMPANY_NAME { get; set; }
        public string CUSTOMER_CONTACTPERSON { get; set; }
        public string CUSTOMER_ADDRESS { get; set; }
        public string CUSTOMER_TEL { get; set; }
        public System.DateTime DELIVERY_DATE { get; set; }
        public string ORIGIN_ORDER_NUMBER { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string FAX_NUMBER { get; set; }
        public string WAREHOUSETYPE { get; set; }
        public bool IS_TO_SEND { get; set; }
        public int SEND_STATUS { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
        public int PK_SOCOMPANY { get; set; }
        public int SO_STATUS { get; set; }
        public System.DateTime CREATE_DATETIME { get; set; }
        public Nullable<System.DateTime> TAKE_OVER_DATETIME { get; set; }
        public bool ISHURRY { get; set; }
        public string FROM_CITY_NAME { get; set; }
        public string FROM_CITY_CODE { get; set; }
        public string TO_CITY_NAME { get; set; }
        public string TO_CITY_CODE { get; set; }
        public bool IS_PRINT_SO { get; set; }
        public string DO_USER { get; set; }
        public string WAREHOUSE_CODE { get; set; }
        public int EXCEL_STATUS { get; set; }
        public Nullable<System.DateTime> EXCEL_DATE { get; set; }
        public bool IS_BLP { get; set; }
        public string DELIVERY_REMARK { get; set; }
        public Nullable<int> SOPACK_QUANTITY { get; set; }
        public int FTP_STATUS { get; set; }
        public Nullable<int> TRIPPACK_QUANTITY { get; set; }
        public string OU_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SODETAIL> SODETAILs { get; set; }
    }
}
